-- MySQL Script generated by MySQL Workbench
-- Sun Sep 18 22:47:55 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema twittterdb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema twittterdb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `twittterdb` DEFAULT CHARACTER SET utf8 ;
USE `twittterdb` ;

-- -----------------------------------------------------
-- Table `twittterdb`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `twittterdb`.`users` (
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `first_name` VARCHAR(45) NULL,
  `last_name` VARCHAR(45) NULL,
  `dob` VARCHAR(45) NULL,
  PRIMARY KEY (`username`),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `twittterdb`.`blocked_users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `twittterdb`.`blocked_users` (
  `users_username` VARCHAR(45) NOT NULL,
  `blocked_username` VARCHAR(45) NULL,
  PRIMARY KEY (`users_username`),
  CONSTRAINT `fk_blocked_users_users1`
    FOREIGN KEY (`users_username`)
    REFERENCES `twittterdb`.`users` (`username`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `twittterdb`.`tweets`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `twittterdb`.`tweets` (
  `tweet_id` INT NOT NULL AUTO_INCREMENT,
  `content` VARCHAR(45) NOT NULL,
  `likes` INT NULL,
  `users_username` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`tweet_id`, `users_username`),
  INDEX `fk_tweets_users_idx` (`users_username` ASC) VISIBLE,
  UNIQUE INDEX `tweet_id_UNIQUE` (`tweet_id` ASC) VISIBLE,
  CONSTRAINT `fk_tweets_users`
    FOREIGN KEY (`users_username`)
    REFERENCES `twittterdb`.`users` (`username`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `twittterdb`.`followed_users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `twittterdb`.`followed_users` (
  `followed_usernam` VARCHAR(45) NOT NULL,
  `users_username` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`followed_usernam`, `users_username`),
  INDEX `fk_followed_users_users1_idx` (`users_username` ASC) VISIBLE,
  CONSTRAINT `fk_followed_users_users1`
    FOREIGN KEY (`users_username`)
    REFERENCES `twittterdb`.`users` (`username`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `twittterdb`.`liked_tweets`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `twittterdb`.`liked_tweets` (
  `users_username` VARCHAR(45) NOT NULL,
  `tweets_tweet_id` INT NOT NULL,
  `tweets_users_username` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`users_username`, `tweets_tweet_id`, `tweets_users_username`),
  INDEX `fk_users_has_tweets_tweets1_idx` (`tweets_tweet_id` ASC, `tweets_users_username` ASC) VISIBLE,
  INDEX `fk_users_has_tweets_users1_idx` (`users_username` ASC) VISIBLE,
  CONSTRAINT `fk_users_has_tweets_users1`
    FOREIGN KEY (`users_username`)
    REFERENCES `twittterdb`.`users` (`username`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_users_has_tweets_tweets1`
    FOREIGN KEY (`tweets_tweet_id` , `tweets_users_username`)
    REFERENCES `twittterdb`.`tweets` (`tweet_id` , `users_username`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `twittterdb`.`liked_tweets`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `twittterdb`.`liked_tweets` (
  `users_username` VARCHAR(45) NOT NULL,
  `tweets_tweet_id` INT NOT NULL,
  `tweets_users_username` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`users_username`, `tweets_tweet_id`, `tweets_users_username`),
  INDEX `fk_users_has_tweets_tweets1_idx` (`tweets_tweet_id` ASC, `tweets_users_username` ASC) VISIBLE,
  INDEX `fk_users_has_tweets_users1_idx` (`users_username` ASC) VISIBLE,
  CONSTRAINT `fk_users_has_tweets_users1`
    FOREIGN KEY (`users_username`)
    REFERENCES `twittterdb`.`users` (`username`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_users_has_tweets_tweets1`
    FOREIGN KEY (`tweets_tweet_id` , `tweets_users_username`)
    REFERENCES `twittterdb`.`tweets` (`tweet_id` , `users_username`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
